// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Jm2QCDIqs56GX1q2Xw3FwmajlOvjj7U',
    appId: '1:686958587861:web:a572cadd3528de60cc575c',
    messagingSenderId: '686958587861',
    projectId: 'e-commerce-app-c9a26',
    authDomain: 'e-commerce-app-c9a26.firebaseapp.com',
    storageBucket: 'e-commerce-app-c9a26.firebasestorage.app',
    measurementId: 'G-0YBX9B85XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0y2cv0PFI85DGZ7ewCEokllqZQCMNwo',
    appId: '1:686958587861:android:6364894fcb05836dcc575c',
    messagingSenderId: '686958587861',
    projectId: 'e-commerce-app-c9a26',
    storageBucket: 'e-commerce-app-c9a26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmCOd8iZ8oGE7qkT3oWXHpBt0fsf78VyE',
    appId: '1:686958587861:ios:edc3336b55fb32a2cc575c',
    messagingSenderId: '686958587861',
    projectId: 'e-commerce-app-c9a26',
    storageBucket: 'e-commerce-app-c9a26.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Jm2QCDIqs56GX1q2Xw3FwmajlOvjj7U',
    appId: '1:686958587861:web:512832a24953c5e6cc575c',
    messagingSenderId: '686958587861',
    projectId: 'e-commerce-app-c9a26',
    authDomain: 'e-commerce-app-c9a26.firebaseapp.com',
    storageBucket: 'e-commerce-app-c9a26.firebasestorage.app',
    measurementId: 'G-KSPT67PY5K',
  );
}
